# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
 
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "r8169" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-11a73e03-d2e6-4fac-a4af-bd5826de4770";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-11a73e03-d2e6-4fac-a4af-bd5826de4770".device = "/dev/disk/by-uuid/11a73e03-d2e6-4fac-a4af-bd5826de4770";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C02D-4E5C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  environment.etc."crypttab".text = ''
    crypt_build /dev/disk/by-uuid/51a0e010-db4a-4db9-a05f-66d84eac604b none nofail
  '';

  fileSystems."/media/build" = {
      device = "/dev/disk/by-uuid/89868ab6-90ae-4e80-838a-c8802e64857a";
      fsType = "ext4";
      options = [ "nofail" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
